# Generated by Django 4.0.4 on 2022-05-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0002_alter_storedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='file',
            field=models.FileField(upload_to='', verbose_name='file'),
        ),
    ]
